### PR TITLE
Capitalized Neutral in Carbon Neutral

### PR DESCRIPTION
**Pull request by koqel**

### CODE REVIEW

**Comment by imlayered** [comment]
mmmm no

**Comment by koqel** [comment]
8d95c9dc-26b0-4233-a8f4-7b86ab5d22a1

**Comment by Cartyoo** [comment]
i agree, you should not approve this. it does not deserve to be capitalized because colton made it

**Comment by imlayered** [comment]
car

**Comment by Cartyoo** [comment]
caar

**Pull request merged**
